# Generated by Django 6.0 on 2026-09-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_contactmessage_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
